<!-- Below is the popup container.  -->
<?php
$m_html = "<div class=\"wisdm-popup-container\"><div class=\"wisdm-content-wrap\">";
$m_html .= "<span class=\"wisdm-close\">&#10006;</span><div class=\"popup_content\">";
$m_html .= "<div style='display:none;' class=\"popup_form_content\"><h4>Please put down your questions in the message box below</h4>" . do_shortcode('[contact-form-7 id="383483"]') ."</div>";
$m_html .= "<div class='popup_desc_content'><h3>100% No-Risk 15 Day Money-back Guarantee</h3><p>";
$m_html .= "You are fully protected by our 100% No-Risk 15 Day money-back guarantee.";
$m_html .= " If you think this does not fulfil your requirements, ";
$m_html .= "just let us know and we will immediately issue a refund. ";
$m_html .= "You get a great return on investment or your money back. </p>";
$m_html .= "<button class=\"wisdm-complete\">Complete purchase</button><br>";
$m_html .= "<a class='have-some-q' href=\"/contact-us/#say-hello\">Have some questions </a></div></div></div></div>";
$m_html .= "<style id='cta-popup-style-376176'>.popup_form_content div.wpcf7 .screen-reader-response{position:absolute;overflow:hidden;clip:rect(1px,1px,1px,1px);height:1px;width:1px;margin:0;padding:0;border:0}.popup_form_content div.wpcf7-response-output{margin:2em .5em 1em;padding:.2em 1em;border:2px solid red}.popup_form_content div.wpcf7-mail-sent-ok{border:2px solid #398f14}.popup_form_content div.wpcf7-aborted,.popup_form_content div.wpcf7-mail-sent-ng{border:2px solid red}.popup_form_content div.wpcf7-spam-blocked{border:2px solid orange}.popup_form_content div.wpcf7-acceptance-missing,div.wpcf7-validation-errors{border:2px solid #f7e700}.popup_form_content .wpcf7-form-control-wrap{position:relative}.popup_form_content .use-floating-validation-tip span.wpcf7-not-valid-tip{position:absolute;top:20%;left:20%;z-index:100;border:1px solid red;background:#fff;padding:.2em .8em}.popup_form_content span.wpcf7-list-item{display:inline-block;margin:0 0 0 1em}.popup_form_content span.wpcf7-list-item-label:after,.popup_form_content span.wpcf7-list-item-label:before{content:''}.popup_form_content .wpcf7-display-none{display:none}.popup_form_content div.wpcf7 .ajax-loader{visibility:hidden;display:inline-block;background-image:url(wp-content/plugins/contact-form-7/images/ajax-loader.gif);width:16px;height:16px;border:none;padding:0;margin:0 0 0 4px;vertical-align:middle}.popup_form_content div.wpcf7 .ajax-loader.is-active{visibility:visible}div.wpcf7 div.ajax-error{display:none}div.wpcf7 .placeheld{color:#888}.popup_form_content div.wpcf7 input,.popup_form_content div.wpcf7 textarea[type=file]{cursor:pointer}.popup_form_content div.wpcf7 .wpcf7-submit:disabled{cursor:not-allowed}.popup_form_content span.wpcf7-not-valid-tip{position:relative}.popup_form_content span.your-name input,.popup_form_content span.your-email input,.popup_form_content span.your-message textarea{padding: 4%;}.popup_form_content input.wpcf7-form-control,.popup_form_content textarea.wpcf7-form-control {border-radius: 3px !important;}.popup_form_content span.wpcf7-list-item{display:inline-block;margin: 0 0 0 1em;}.popup_form_content .one-half .cf-label{display: none}.popup_form_content .cf-label{float:none;text-transform:inherit;top:inherit;z-index:inherit;left:inherit;font-size:inherit;padding:inherit;}.popup_form_content input{height:inherit !important}.popup_form_content p{margin-bottom:2.6rem}.popup_form_content span.wpcf7-list-item.first,.popup_form_content span.wpcf7-list-item.last {width: 46%;}</style>";
$m_html .= "<script>jQuery('.have-some-q').on('click',function(e){e.preventDefault();jQuery('.wisdm-popup-container .popup_desc_content').hide();jQuery('.wisdm-popup-container .popup_form_content').show();});document.addEventListener( 'wpcf7mailsent', function( event ) { document.querySelector('.wisdm-popup-container .wisdm-close').click(); }, false );</script>";
echo $m_html;
?>
